name: Java CI

on:
  push:
    branches: [ 6.0 ]
  pull_request:
    branches: [ 6.0 ]
  workflow_dispatch:
    branches: [ 6.0 ]

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up PATH
      run: |
        echo "${ANDROID_HOME}/build-tools/30.0.1" >> $GITHUB_PATH
        echo "REPOSITORY_NAME=portal" >> $GITHUB_ENV
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Build mod jar
      run: chmod +x gradlew; ./gradlew deploy
    - name: Upload built jar file
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.REPOSITORY_NAME }}
        path: build/libs/${{ env.REPOSITORY_NAME }}.jar
